# permissions for end users to edit argocds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/managed-by: kustomize
  name: argocd-editor-role
rules:
- apiGroups:
  - demo.kw.local
  resources:
  - argocds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.kw.local
  resources:
  - argocds/status
  verbs:
  - get
