apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: gitea-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - namespaces
  - networkpolicies
  - poddisruptionbudgets
  - secrets
  - events
  - deployments
  - statefulsets
  - configmaps
  - persistentvolumeclaims
  - serviceaccounts
  - services
  - gitea
  - gitea/status
  - gitea/finalizers
  verbs:
  - '*'
