# permissions for end users to edit nexuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nexus
    app.kubernetes.io/managed-by: kustomize
  name: nexus-editor-role
rules:
- apiGroups:
  - demo.kw.local
  resources:
  - nexuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.kw.local
  resources:
  - nexuses/status
  verbs:
  - get
