# permissions for end users to edit apaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: apache
    app.kubernetes.io/managed-by: kustomize
  name: apache-editor-role
rules:
- apiGroups:
  - demo.kw.local
  resources:
  - apaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.kw.local
  resources:
  - apaches/status
  verbs:
  - get
