apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"harbor"},"name":"harbor-manager-rolebinding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"harbor-manager-role"},"subjects":[{"kind":"ServiceAccount","name":"harbor-controller-manager","namespace":"harbor-system"}]}
  creationTimestamp: "2025-01-19T00:43:24Z"
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: harbor
  name: harbor-manager-rolebinding-2
  resourceVersion: "326647"
  uid: b473c780-b50e-44eb-b7b6-e4d29e2df223
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: harbor-controller-manager
  namespace: harbor-system
