# permissions for end users to view harbors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/managed-by: kustomize
  name: harbor-viewer-role
rules:
- apiGroups:
  - demo.kw.local
  resources:
  - harbors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.kw.local
  resources:
  - harbors/status
  verbs:
  - get
